---
title: "Tugas 1"
author: "Butsainah Taqiah"
date: "2023-09-05"
output: html_document
---
```{r}
library("forecast")
library("graphics")
library("TTR")
library("TSA")
library("rio")
```

```{r}
#import data
data1 <- import("https://raw.githubusercontent.com/Taqiiiii/mpdw1/main/DATA%20PRAK%201%20MPDW/Data%20Suhu%20Pekanbaru%202022.csv")
data1
```

```{r}
## Eksplorasi Data

View(data1)
str(data1)
dim(data1)

```
```{r}
#Mengubah data agar terbaca sebagai data deret waktu dengan fungsi `ts()` .
data1.ts <- ts(data1$suhu)
data1.ts
summary(data1.ts)
```
```{r}
#Membuat plot data deret waktu
ts.plot(data1.ts, xlab="periode ", ylab="suhu", 
        main = "Time Series Plot")
points(data1.ts)
```
```{r}
## Single Moving Average 
### Pembagian Data
#### Pembagian data latih dan data uji dilakukan dengan perbandingan 80% data latih dan 20% data uji.
training_ma <- data1[1:292,]
testing_ma <- data1[293:365,]
train_ma.ts <- ts(training_ma$suhu)
test_ma.ts <- ts(testing_ma$suhu)
```

```{r}
### Eksplorasi Data
#### Eksplorasi data dilakukan pada keseluruhan data, data latih serta data uji menggunakan plot data deret waktu.

#eksplorasi keseluruhan data
plot(data1.ts, col="red",main="Plot semua data")
points(data1.ts)

#eksplorasi data latih
plot(train_ma.ts, col="blue",main="Plot data latih")
points(train_ma.ts)

#eksplorasi data uji
plot(test_ma.ts, col="blue",main="Plot data uji")
points(test_ma.ts)

```
```{r}
### Single Moving Average (SMA)
#### Ide dasar dari Single Moving Average (SMA) adalah data suatu periode dipengaruhi oleh data periode sebelumnya. Metode pemulusan ini cocok digunakan untuk pola data stasioner atau konstan. Prinsip dasar metode pemulusan ini adalah data pemulusan pada periode ke-t merupakan rata rata dari m buah data pada periode ke-t hingga periode ke (t-m+1). Data pemulusan pada periode ke-t selanjutnya digunakan sebagai nilai peramalan pada periode ke t+1
###### Pemulusan menggunakan metode SMA dilakukan dengan fungsi `SMA()`. Dalam hal ini akan dilakukan pemulusan dengan parameter `m=4`.

data.sma<-SMA(train_ma.ts, n=4)
data.sma

##Data pemulusan pada periode ke-t selanjutnya digunakan sebagai nilai peramalan pada periode ke t+1 sehingga hasil peramalan 1 periode kedepan adalah sebagai berikut.

data.ramal<-c(NA,data.sma)
data.ramal #forecast 1 periode ke depan
```

```{r}
#Selanjutnya akan dilakukan peramalan sejumlah data uji yaitu 73 periode. Pada metode SMA, hasil peramalan 73 periode ke depan akan bernilai sama dengan hasil peramalan 1 periode kedepan. Dalam hal ini akan dilakukan penggabungan data aktual train, data hasil pemulusan dan data hasil ramalan 73 periode kedepan.

data.gab<-cbind(aktual=c(train_ma.ts,rep(NA,73)),pemulusan=c(data.sma,rep(NA,73)),ramalan=c(data.ramal,rep(data.ramal[length(data.ramal)],72)))
data.gab #forecast 73 periode ke depan
```
```{r}
#Adapun plot data deret waktu dari hasil peramalan yang dilakukan adalah sebagai berikut.

ts.plot(data1.ts, xlab="Time Period ", ylab="suhu", main= "SMA N=4 data suhu")
points(data1.ts)
lines(data.gab[,2],col="green",lwd=2)
lines(data.gab[,3],col="red",lwd=2)
legend("topleft",c("data aktual","data pemulusan","data peramalan"), lty=8, col=c("black","green","red"), cex=0.5)
```
```{r}
## Selanjutnya perhitungan akurasi dilakukan dengan ukuran akurasi *Sum Squares Error* (SSE), *Mean Square Error* (MSE) dan *Mean Absolute Percentage Error* (MAPE). Perhitungan akurasi dilakukan baik pada data latih maupun pada data uji.

#Menghitung nilai keakuratan data latih
error_train.sma = train_ma.ts-data.ramal[1:length(train_ma.ts)]
SSE_train.sma = sum(error_train.sma[5:length(train_ma.ts)]^2)
MSE_train.sma = mean(error_train.sma[5:length(train_ma.ts)]^2)
MAPE_train.sma = mean(abs((error_train.sma[5:length(train_ma.ts)]/train_ma.ts[5:length(train_ma.ts)])*100))

akurasi_train.sma <- matrix(c(SSE_train.sma, MSE_train.sma, MAPE_train.sma))
row.names(akurasi_train.sma)<- c("SSE", "MSE", "MAPE")
colnames(akurasi_train.sma) <- c("Akurasi m = 4")
akurasi_train.sma
```
```{r}
#Dalam hal ini nilai MAPE data latih pada metode pemulusan SMA kurang dari 2%, nilai ini dapat dikategorikan sebagai nilai akurasi yang sangat baik. Selanjutnya dilakukan perhitungan nilai MAPE data uji pada metde pemulusan SMA.

#Menghitung nilai keakuratan data uji
error_test.sma = test_ma.ts-data.gab[293:365,3]
SSE_test.sma = sum(error_test.sma^2)
MSE_test.sma = mean(error_test.sma^2)
MAPE_test.sma = mean(abs((error_test.sma/test_ma.ts*100)))

akurasi_test.sma <- matrix(c(SSE_test.sma, MSE_test.sma, MAPE_test.sma))
row.names(akurasi_test.sma)<- c("SSE", "MSE", "MAPE")
colnames(akurasi_test.sma) <- c("Akurasi m = 4")
akurasi_test.sma

##Perhitungan akurasi menggunakan data latih menghasilkan nilai MAPE yang kurang dari 10% sehingga nilai akurasi ini dapat dikategorikan sebagai sangat baik.
```